/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.ifrn.sc.pds.moviecrud.ui;

import br.edu.ifrn.sc.pds.moviecrud.dominio.Filme;
import br.edu.ifrn.sc.pds.moviecrud.persistencia.FilmeDAO;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author tiagorodrigues
 */
public class TelaFilmes extends javax.swing.JFrame {

    /**
     * Creates new form TelaFilmes
     */
    public TelaFilmes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfTitulo = new javax.swing.JTextField();
        jtfDuracao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfAvaliacao = new javax.swing.JTextField();
        jtfAno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jbtnDelete = new javax.swing.JToggleButton();
        jbtnSave = new javax.swing.JToggleButton();
        jbtnEdit = new javax.swing.JToggleButton();
        jbtnList = new javax.swing.JToggleButton();
        jbtnSearch = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaFilmes = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(4, 7, 20));

        jLabel1.setBackground(new java.awt.Color(19, 21, 29));
        jLabel1.setFont(new java.awt.Font("Fira Sans", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 99, 229));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MyMovies");
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(256, 56));

        jLabel2.setFont(new java.awt.Font("Fira Sans", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(249, 249, 249));
        jLabel2.setText("Duração (min)");

        jtfTitulo.setBackground(new java.awt.Color(19, 21, 29));
        jtfTitulo.setFont(new java.awt.Font("Fira Sans", 0, 16)); // NOI18N
        jtfTitulo.setForeground(new java.awt.Color(249, 249, 249));
        jtfTitulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 99, 229)));
        jtfTitulo.setCaretColor(new java.awt.Color(0, 99, 229));
        jtfTitulo.setMargin(new java.awt.Insets(4, 8, 4, 8));
        jtfTitulo.setPreferredSize(new java.awt.Dimension(560, 40));
        jtfTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfTituloActionPerformed(evt);
            }
        });

        jtfDuracao.setBackground(new java.awt.Color(19, 21, 29));
        jtfDuracao.setFont(new java.awt.Font("Fira Sans", 0, 16)); // NOI18N
        jtfDuracao.setForeground(new java.awt.Color(249, 249, 249));
        jtfDuracao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 99, 229)));
        jtfDuracao.setCaretColor(new java.awt.Color(0, 99, 229));
        jtfDuracao.setMargin(new java.awt.Insets(4, 8, 4, 8));
        jtfDuracao.setPreferredSize(new java.awt.Dimension(560, 40));
        jtfDuracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDuracaoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Fira Sans", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(249, 249, 249));
        jLabel3.setText("Título");

        jtfAvaliacao.setBackground(new java.awt.Color(19, 21, 29));
        jtfAvaliacao.setFont(new java.awt.Font("Fira Sans", 0, 16)); // NOI18N
        jtfAvaliacao.setForeground(new java.awt.Color(249, 249, 249));
        jtfAvaliacao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 99, 229)));
        jtfAvaliacao.setCaretColor(new java.awt.Color(0, 99, 229));
        jtfAvaliacao.setMargin(new java.awt.Insets(4, 8, 4, 8));
        jtfAvaliacao.setPreferredSize(new java.awt.Dimension(560, 40));
        jtfAvaliacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfAvaliacaoActionPerformed(evt);
            }
        });

        jtfAno.setBackground(new java.awt.Color(19, 21, 29));
        jtfAno.setFont(new java.awt.Font("Fira Sans", 0, 16)); // NOI18N
        jtfAno.setForeground(new java.awt.Color(249, 249, 249));
        jtfAno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 99, 229)));
        jtfAno.setCaretColor(new java.awt.Color(0, 99, 229));
        jtfAno.setMargin(new java.awt.Insets(4, 8, 4, 8));
        jtfAno.setPreferredSize(new java.awt.Dimension(560, 40));
        jtfAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfAnoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Fira Sans", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(249, 249, 249));
        jLabel4.setText("Ano");

        jLabel5.setFont(new java.awt.Font("Fira Sans", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(249, 249, 249));
        jLabel5.setText("Avaliação");

        jbtnDelete.setBackground(new java.awt.Color(0, 99, 229));
        jbtnDelete.setFont(new java.awt.Font("Fira Sans", 1, 16)); // NOI18N
        jbtnDelete.setForeground(new java.awt.Color(249, 249, 249));
        jbtnDelete.setText("Remover");
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });

        jbtnSave.setBackground(new java.awt.Color(0, 99, 229));
        jbtnSave.setFont(new java.awt.Font("Fira Sans", 1, 16)); // NOI18N
        jbtnSave.setForeground(new java.awt.Color(249, 249, 249));
        jbtnSave.setText("Salvar");
        jbtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSaveActionPerformed(evt);
            }
        });

        jbtnEdit.setBackground(new java.awt.Color(0, 99, 229));
        jbtnEdit.setFont(new java.awt.Font("Fira Sans", 1, 16)); // NOI18N
        jbtnEdit.setForeground(new java.awt.Color(249, 249, 249));
        jbtnEdit.setText("Editar");
        jbtnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEditActionPerformed(evt);
            }
        });

        jbtnList.setBackground(new java.awt.Color(0, 99, 229));
        jbtnList.setFont(new java.awt.Font("Fira Sans", 1, 16)); // NOI18N
        jbtnList.setForeground(new java.awt.Color(249, 249, 249));
        jbtnList.setText("Listar");
        jbtnList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnListActionPerformed(evt);
            }
        });

        jbtnSearch.setBackground(new java.awt.Color(0, 99, 229));
        jbtnSearch.setFont(new java.awt.Font("Fira Sans", 1, 16)); // NOI18N
        jbtnSearch.setForeground(new java.awt.Color(249, 249, 249));
        jbtnSearch.setText("Buscar");
        jbtnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSearchActionPerformed(evt);
            }
        });

        jtaFilmes.setEditable(false);
        jtaFilmes.setBackground(new java.awt.Color(19, 21, 29));
        jtaFilmes.setColumns(20);
        jtaFilmes.setFont(new java.awt.Font("Fira Sans", 0, 14)); // NOI18N
        jtaFilmes.setForeground(new java.awt.Color(249, 249, 249));
        jtaFilmes.setRows(5);
        jtaFilmes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 99, 229)));
        jScrollPane2.setViewportView(jtaFilmes);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnList, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtfTitulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(128, 128, 128)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfAno, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jtfAvaliacao, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jbtnSave, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(8, 8, 8)
                        .addComponent(jtfTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfAvaliacao, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfAno, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addComponent(jbtnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jbtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jbtnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnList, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2))
                .addGap(35, 35, 35))
        );

        jLabel1.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfTituloActionPerformed

    private void jtfDuracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDuracaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDuracaoActionPerformed

    private void jtfAvaliacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfAvaliacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfAvaliacaoActionPerformed

    private void jtfAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfAnoActionPerformed

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed
        String titulo = jtfTitulo.getText();

        FilmeDAO filmeDao = new FilmeDAO();
        Filme filme = null;

        if (titulo.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Insira um título para deletar");
        } else {
            filme = filmeDao.buscarFilme(titulo);

            if (filme == null) {
                JOptionPane.showMessageDialog(rootPane, "Este título não foi encontrado");
                return;
            }

            boolean response = filmeDao.removerFilme(filme.getId());

            if (response) {
                JOptionPane.showMessageDialog(rootPane, "Filme deletado com sucesso!");

                jtfTitulo.setText("");
                jtfDuracao.setText("");
                jtfAno.setText("");
                jtfAvaliacao.setText("");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Não foi possível deletar seu filme!");
            }
        }
    }//GEN-LAST:event_jbtnDeleteActionPerformed

    private void jbtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSaveActionPerformed
        String titulo = jtfTitulo.getText();
        String campoDuracao = jtfDuracao.getText();
        String campoAno = jtfAno.getText();
        String campoAvaliacao = jtfAvaliacao.getText();

        int duracao, ano;
        double avaliacao;

        Filme filme = null;
        FilmeDAO filmeDao = new FilmeDAO();

        if (!titulo.isEmpty() && !campoDuracao.isEmpty() && !campoAno.isEmpty() && !campoAvaliacao.isEmpty()) {
            filme = filmeDao.buscarFilme(titulo);

            if (filme != null) {
                JOptionPane.showMessageDialog(rootPane, "Este título já está cadastrado");
                return;
            }

            duracao = Integer.parseInt(campoDuracao);
            ano = Integer.parseInt(campoAno);
            avaliacao = Double.parseDouble(campoAvaliacao);
            
            filme = new Filme(titulo, duracao, ano, avaliacao);
            boolean response = filmeDao.inserirFilme(filme);

            if (response) {
                JOptionPane.showMessageDialog(rootPane, "Filme salvo com sucesso!");

                jtfTitulo.setText("");
                jtfDuracao.setText("");
                jtfAno.setText("");
                jtfAvaliacao.setText("");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Não foi possível salvar seu filme!");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Preencha todos os campos com os valores desejados");
        
        }
    }//GEN-LAST:event_jbtnSaveActionPerformed

    private void jbtnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEditActionPerformed
        String titulo = jtfTitulo.getText();
        String campoDuracao = jtfDuracao.getText();
        String campoAno = jtfAno.getText();
        String campoAvaliacao = jtfAvaliacao.getText();

        int duracao, ano;
        double avaliacao;

        Filme filme = null;
        FilmeDAO filmeDao = new FilmeDAO();

        if (titulo.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Insira um título para editar");
        } else {
            filme = filmeDao.buscarFilme(titulo);

            if (filme == null) {
                JOptionPane.showMessageDialog(rootPane, "Este título não está cadastrado");
                return;
            }

            jtfAno.setText(String.valueOf(filme.getAno()));
            jtfDuracao.setText(String.valueOf(filme.getDuracao()));
            jtfAvaliacao.setText(String.valueOf(filme.getAvaliacao()));
        }

        if (!campoDuracao.isEmpty() && !campoAno.isEmpty() && !campoAvaliacao.isEmpty()) {
            duracao = Integer.parseInt(campoDuracao);
            ano = Integer.parseInt(campoAno);
            avaliacao = Double.parseDouble(campoAvaliacao);

            filme.setDuracao(duracao);
            filme.setAno(ano);
            filme.setAvaliacao(avaliacao);

            boolean response = filmeDao.alterarFilme(filme);

            if (response) {
                JOptionPane.showMessageDialog(rootPane, "Filme editado com sucesso!");

                jtfTitulo.setText("");
                jtfDuracao.setText("");
                jtfAno.setText("");
                jtfAvaliacao.setText("");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Não foi possível editar seu filme!");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Preencha todos os campos com os valores desejados");
        }
    }//GEN-LAST:event_jbtnEditActionPerformed

    private void jbtnListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnListActionPerformed
        jtaFilmes.setText("");

        FilmeDAO filmeDao = new FilmeDAO();
        List<Filme> filmes = filmeDao.listarFilmes();

        for (Filme filme : filmes) {
            jtaFilmes.append(filme.toString() + "\n");
        }

    }//GEN-LAST:event_jbtnListActionPerformed

    private void jbtnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSearchActionPerformed
        String titulo = jtfTitulo.getText();

        FilmeDAO filmeDao = new FilmeDAO();
        Filme filme = null;

        if (titulo.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Insira um título para editar");
        } else {
            filme = filmeDao.buscarFilme(titulo);

            if (filme == null) {
                JOptionPane.showMessageDialog(rootPane, "Este título não está cadastrado");
                return;
            }

            jtfAno.setText(String.valueOf(filme.getAno()));
            jtfDuracao.setText(String.valueOf(filme.getDuracao()));
            jtfAvaliacao.setText(String.valueOf(filme.getAvaliacao()));
        }
    }//GEN-LAST:event_jbtnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFilmes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFilmes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jbtnDelete;
    private javax.swing.JToggleButton jbtnEdit;
    private javax.swing.JToggleButton jbtnList;
    private javax.swing.JToggleButton jbtnSave;
    private javax.swing.JToggleButton jbtnSearch;
    private javax.swing.JTextArea jtaFilmes;
    private javax.swing.JTextField jtfAno;
    private javax.swing.JTextField jtfAvaliacao;
    private javax.swing.JTextField jtfDuracao;
    private javax.swing.JTextField jtfTitulo;
    // End of variables declaration//GEN-END:variables
}
